// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: Standby

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void clockWise_Animation( lv_obj_t *TargetObject, int delay);
void pulseCall_Animation( lv_obj_t *TargetObject, int delay);
void textUpDown_Animation( lv_obj_t *TargetObject, int delay);
void textSide_Animation( lv_obj_t *TargetObject, int delay);
void ui_event_homeScreen( lv_event_t * e);
lv_obj_t *ui_homeScreen;
lv_obj_t *ui_clockSmallBackground;
lv_obj_t *ui_hourHand;
lv_obj_t *ui_minuteHand;
lv_obj_t *ui_secondHand;
lv_obj_t *ui_clockDot;
lv_obj_t *ui_infoPanel;
lv_obj_t *ui_weatherPanel;
lv_obj_t *ui_weatherCity;
lv_obj_t *ui_weatherTemperature;
lv_obj_t *ui_weatherIcon;
lv_obj_t *ui_weatherCondition;
lv_obj_t *ui_weatherRange;
lv_obj_t *ui_calendar;
lv_obj_t *ui_musicPanel;
void ui_event_previosButton( lv_event_t * e);
lv_obj_t *ui_previosButton;
void ui_event_playPause( lv_event_t * e);
lv_obj_t *ui_playPause;
void ui_event_nextButton( lv_event_t * e);
lv_obj_t *ui_nextButton;
void ui_event_volumeSlider( lv_event_t * e);
lv_obj_t *ui_volumeSlider;
lv_obj_t *ui_alertPanel;
lv_obj_t *ui_alertTitle;
lv_obj_t *ui_alertIcon;
lv_obj_t *ui_alertText;
lv_obj_t *ui_callPanel;
lv_obj_t *ui_callIcon;
lv_obj_t *ui_callText;
lv_obj_t *ui_callerName;
void ui_event_clockScreen( lv_event_t * e);
lv_obj_t *ui_clockScreen;
lv_obj_t *ui_clockPanel;
lv_obj_t *ui_digitalClock2;
lv_obj_t *ui_minute2;
lv_obj_t *ui_hour1;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_minute1;
lv_obj_t *ui_hour2;
lv_obj_t *ui_digitalClock1;
lv_obj_t *ui_analogClock;
lv_obj_t *ui_hourHand1;
lv_obj_t *ui_minuteHand1;
lv_obj_t *ui_secondHand1;
lv_obj_t *ui_clockDot1;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_372661864[7] = {&ui_img_602206286, &ui_img_602205261, &ui_img_602199888, &ui_img_602207311, &ui_img_602200913, &ui_img_602195540, &ui_img_602202963};
const lv_img_dsc_t *ui_imgset_dy[1] = {&ui_img_dy4_png};
const lv_img_dsc_t *ui_imgset_419715717[8] = {&ui_img_229834011, &ui_img_229835036, &ui_img_229827613, &ui_img_229828638, &ui_img_229838359, &ui_img_229839384, &ui_img_229831961, &ui_img_229832986};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void clockWise_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 60000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_0, 0, 3600 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle );
lv_anim_start(&PropertyAnimation_0);

}
void pulseCall_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom );
lv_anim_set_values(&PropertyAnimation_0, 0, 150 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 1000);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_zoom );
lv_anim_start(&PropertyAnimation_0);

}
void textUpDown_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, 0, 20 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 1000);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y );
lv_anim_start(&PropertyAnimation_0);

}
void textSide_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 0, 10 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 1000);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_homeScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
      _ui_screen_change( ui_clockScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      homeScreenLoaded( e );
}
}
void ui_event_previosButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      musicPrevious( e );
}
}
void ui_event_playPause( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      musicToggle( e );
}
}
void ui_event_nextButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      musicNext( e );
}
}
void ui_event_volumeSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      volumeChanged( e );
}
}
void ui_event_clockScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
      _ui_screen_change( ui_homeScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
}
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      clockScreenLoaded( e );
}
}

///////////////////// SCREENS ////////////////////
void ui_homeScreen_screen_init(void)
{
ui_homeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_homeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_homeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_homeScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_clockSmallBackground = lv_img_create(ui_homeScreen);
lv_img_set_src(ui_clockSmallBackground, &ui_img_clock_round_bg_png);
lv_obj_set_width( ui_clockSmallBackground, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_clockSmallBackground, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_clockSmallBackground, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_clockSmallBackground, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_clockSmallBackground, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_hourHand = lv_img_create(ui_homeScreen);
lv_img_set_src(ui_hourHand, &ui_img_hour_h_png);
lv_obj_set_width( ui_hourHand, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_hourHand, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_hourHand, 113 );
lv_obj_set_y( ui_hourHand, -40 );
lv_obj_set_align( ui_hourHand, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_hourHand, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_hourHand, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_hourHand,7,90);
lv_img_set_angle(ui_hourHand,270);

ui_minuteHand = lv_img_create(ui_homeScreen);
lv_img_set_src(ui_minuteHand, &ui_img_minute_h_png);
lv_obj_set_width( ui_minuteHand, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_minuteHand, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_minuteHand, 113 );
lv_obj_set_y( ui_minuteHand, -40 );
lv_obj_set_align( ui_minuteHand, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_minuteHand, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_minuteHand, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_minuteHand,7,90);
lv_img_set_angle(ui_minuteHand,900);

ui_secondHand = lv_img_create(ui_homeScreen);
lv_img_set_src(ui_secondHand, &ui_img_second_h_png);
lv_obj_set_width( ui_secondHand, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_secondHand, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_secondHand, 113 );
lv_obj_set_y( ui_secondHand, -40 );
lv_obj_set_align( ui_secondHand, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_secondHand, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_secondHand, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_secondHand,7,90);
lv_obj_set_style_img_recolor(ui_secondHand, lv_color_hex(0xFF8300), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_secondHand, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_clockDot = lv_obj_create(ui_homeScreen);
lv_obj_set_width( ui_clockDot, 15);
lv_obj_set_height( ui_clockDot, 15);
lv_obj_set_x( ui_clockDot, 113 );
lv_obj_set_y( ui_clockDot, 0 );
lv_obj_set_align( ui_clockDot, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_clockDot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_clockDot, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_clockDot, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_clockDot, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_infoPanel = lv_obj_create(ui_homeScreen);
lv_obj_set_width( ui_infoPanel, 240);
lv_obj_set_height( ui_infoPanel, 320);
lv_obj_set_align( ui_infoPanel, LV_ALIGN_RIGHT_MID );
lv_obj_set_flex_flow(ui_infoPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_infoPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_scrollbar_mode(ui_infoPanel, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_infoPanel, LV_DIR_VER);
lv_obj_set_style_radius(ui_infoPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_infoPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_infoPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_infoPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_infoPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_infoPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_infoPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_infoPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_weatherPanel = lv_obj_create(ui_infoPanel);
lv_obj_set_width( ui_weatherPanel, 215);
lv_obj_set_height( ui_weatherPanel, 320);
lv_obj_set_align( ui_weatherPanel, LV_ALIGN_RIGHT_MID );
lv_obj_set_flex_flow(ui_weatherPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_weatherPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_weatherPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_weatherPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_weatherPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_weatherPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_weatherPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_weatherPanel, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_weatherPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_weatherPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_weatherPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_weatherCity = lv_label_create(ui_weatherPanel);
lv_obj_set_width( ui_weatherCity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_weatherCity, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_weatherCity,"Nairobi");
lv_obj_set_style_text_font(ui_weatherCity, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_weatherTemperature = lv_label_create(ui_weatherPanel);
lv_obj_set_width( ui_weatherTemperature, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_weatherTemperature, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_weatherTemperature, 69 );
lv_obj_set_y( ui_weatherTemperature, -52 );
lv_obj_set_align( ui_weatherTemperature, LV_ALIGN_CENTER );
lv_label_set_text(ui_weatherTemperature,"16°");
lv_obj_set_style_text_font(ui_weatherTemperature, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_weatherIcon = lv_img_create(ui_weatherPanel);
lv_img_set_src(ui_weatherIcon, &ui_img_602202963);
lv_obj_set_width( ui_weatherIcon, LV_SIZE_CONTENT);  /// 14
lv_obj_set_height( ui_weatherIcon, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_weatherIcon, 76 );
lv_obj_set_y( ui_weatherIcon, 28 );
lv_obj_set_align( ui_weatherIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_weatherIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_weatherIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_weatherCondition = lv_label_create(ui_weatherPanel);
lv_obj_set_width( ui_weatherCondition, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_weatherCondition, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_weatherCondition, 99 );
lv_obj_set_y( ui_weatherCondition, 70 );
lv_obj_set_align( ui_weatherCondition, LV_ALIGN_CENTER );
lv_label_set_text(ui_weatherCondition,"Cloudy");

ui_weatherRange = lv_label_create(ui_weatherPanel);
lv_obj_set_width( ui_weatherRange, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_weatherRange, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_weatherRange, 79 );
lv_obj_set_y( ui_weatherRange, 97 );
lv_obj_set_align( ui_weatherRange, LV_ALIGN_CENTER );
lv_label_set_text(ui_weatherRange,"H:27° L:16°");

ui_calendar = lv_calendar_create(ui_infoPanel);
lv_calendar_set_today_date(ui_calendar,2023,9,28);
lv_calendar_set_showed_date(ui_calendar,2023,9);
lv_obj_t *ui_calendar_header = lv_calendar_header_arrow_create(ui_calendar);
lv_obj_set_width( ui_calendar, 230);
lv_obj_set_height( ui_calendar, 320);
lv_obj_set_align( ui_calendar, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_calendar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_calendar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_calendar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_calendar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_calendar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_calendar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_calendar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_calendar, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_calendar, 40, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_calendar, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_calendar, 0, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_calendar, 0, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_calendar, 0, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_calendar, 0, LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_musicPanel = lv_obj_create(ui_infoPanel);
lv_obj_set_width( ui_musicPanel, 234);
lv_obj_set_height( ui_musicPanel, 320);
lv_obj_set_align( ui_musicPanel, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_musicPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_musicPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_musicPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_musicPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_musicPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_musicPanel, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_musicPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_musicPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_musicPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_previosButton = lv_img_create(ui_musicPanel);
lv_img_set_src(ui_previosButton, &ui_img_back_png);
lv_obj_set_width( ui_previosButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_previosButton, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_previosButton, -107 );
lv_obj_set_y( ui_previosButton, -20 );
lv_obj_set_align( ui_previosButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_previosButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_previosButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_previosButton,170);
lv_obj_set_style_radius(ui_previosButton, 20, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_previosButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_previosButton, 150, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_previosButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_previosButton, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_previosButton, 10, LV_PART_MAIN| LV_STATE_PRESSED);

ui_playPause = lv_img_create(ui_musicPanel);
lv_img_set_src(ui_playPause, &ui_img_pause_png);
lv_obj_set_width( ui_playPause, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_playPause, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_playPause, -30 );
lv_obj_set_y( ui_playPause, -20 );
lv_obj_set_align( ui_playPause, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_playPause, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_playPause, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_playPause, 20, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_playPause, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_playPause, 150, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_playPause, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_playPause, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_playPause, 10, LV_PART_MAIN| LV_STATE_PRESSED);

ui_nextButton = lv_img_create(ui_musicPanel);
lv_img_set_src(ui_nextButton, &ui_img_next_png);
lv_obj_set_width( ui_nextButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_nextButton, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_nextButton, 50 );
lv_obj_set_y( ui_nextButton, -20 );
lv_obj_set_align( ui_nextButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_nextButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_nextButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_nextButton,170);
lv_obj_set_style_radius(ui_nextButton, 20, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_nextButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_nextButton, 150, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_nextButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_nextButton, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_nextButton, 10, LV_PART_MAIN| LV_STATE_PRESSED);

ui_volumeSlider = lv_slider_create(ui_musicPanel);
lv_slider_set_value( ui_volumeSlider, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_volumeSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_volumeSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_volumeSlider, 201);
lv_obj_set_height( ui_volumeSlider, 20);
lv_obj_set_x( ui_volumeSlider, -22 );
lv_obj_set_y( ui_volumeSlider, 78 );
lv_obj_set_align( ui_volumeSlider, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_volumeSlider, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_volumeSlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_volumeSlider, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_volumeSlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_volumeSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_volumeSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_volumeSlider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_alertPanel = lv_obj_create(ui_homeScreen);
lv_obj_set_width( ui_alertPanel, 400);
lv_obj_set_height( ui_alertPanel, 250);
lv_obj_set_align( ui_alertPanel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_alertPanel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_alertPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_alertPanel, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_alertPanel, 250, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_alertPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_alertTitle = lv_label_create(ui_alertPanel);
lv_obj_set_width( ui_alertTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_alertTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_alertTitle, 65 );
lv_obj_set_y( ui_alertTitle, 1 );
lv_label_set_text(ui_alertTitle,"Whatsapp");
lv_obj_set_style_text_font(ui_alertTitle, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_alertIcon = lv_img_create(ui_alertPanel);
lv_img_set_src(ui_alertIcon, &ui_img_whatsapp_png);
lv_obj_set_width( ui_alertIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_alertIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_alertIcon, -153 );
lv_obj_set_y( ui_alertIcon, -88 );
lv_obj_set_align( ui_alertIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_alertIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_alertIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_alertText = lv_label_create(ui_alertPanel);
lv_obj_set_width( ui_alertText, 343);
lv_obj_set_height( ui_alertText, 169);
lv_obj_set_x( ui_alertText, 10 );
lv_obj_set_y( ui_alertText, 50 );
lv_label_set_long_mode(ui_alertText,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_alertText,"Hello there");
lv_obj_set_style_text_font(ui_alertText, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_callPanel = lv_obj_create(ui_homeScreen);
lv_obj_set_width( ui_callPanel, 416);
lv_obj_set_height( ui_callPanel, 225);
lv_obj_set_align( ui_callPanel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_callPanel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_callPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_callPanel, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_callPanel, 250, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_callPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_callIcon = lv_img_create(ui_callPanel);
lv_img_set_src(ui_callIcon, &ui_img_answer_png);
lv_obj_set_width( ui_callIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_callIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_callIcon, -125 );
lv_obj_set_y( ui_callIcon, 0 );
lv_obj_set_align( ui_callIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_callIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_callIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_callText = lv_label_create(ui_callPanel);
lv_obj_set_width( ui_callText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_callText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_callText, -13 );
lv_obj_set_y( ui_callText, -74 );
lv_obj_set_align( ui_callText, LV_ALIGN_CENTER );
lv_label_set_text(ui_callText,"Incoming Call");

ui_callerName = lv_label_create(ui_callPanel);
lv_obj_set_width( ui_callerName, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_callerName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_callerName, 146 );
lv_obj_set_y( ui_callerName, 0 );
lv_obj_set_align( ui_callerName, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_callerName,"Felix");
lv_obj_set_style_text_font(ui_callerName, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_previosButton, ui_event_previosButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_playPause, ui_event_playPause, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_nextButton, ui_event_nextButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_volumeSlider, ui_event_volumeSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_homeScreen, ui_event_homeScreen, LV_EVENT_ALL, NULL);

}
void ui_clockScreen_screen_init(void)
{
ui_clockScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_clockScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_clockScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_clockScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_clockPanel = lv_obj_create(ui_clockScreen);
lv_obj_set_width( ui_clockPanel, 480);
lv_obj_set_height( ui_clockPanel, 320);
lv_obj_set_align( ui_clockPanel, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_clockPanel,LV_FLEX_FLOW_COLUMN_REVERSE);
lv_obj_set_flex_align(ui_clockPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_clockPanel, LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_clockPanel, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_clockPanel, LV_DIR_VER);
lv_obj_set_style_radius(ui_clockPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_clockPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_clockPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_clockPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_clockPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_clockPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_clockPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_clockPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_digitalClock2 = lv_obj_create(ui_clockPanel);
lv_obj_set_width( ui_digitalClock2, 480);
lv_obj_set_height( ui_digitalClock2, 320);
lv_obj_set_align( ui_digitalClock2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_digitalClock2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_digitalClock2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_digitalClock2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_digitalClock2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_digitalClock2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_minute2 = lv_img_create(ui_digitalClock2);
lv_img_set_src(ui_minute2, &ui_img_a_zero_png);
lv_obj_set_width( ui_minute2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_minute2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_minute2, 150 );
lv_obj_set_y( ui_minute2, 0 );
lv_obj_set_align( ui_minute2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_minute2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_minute2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_hour1 = lv_img_create(ui_digitalClock2);
lv_img_set_src(ui_hour1, &ui_img_a_zero_png);
lv_obj_set_width( ui_hour1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_hour1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_hour1, -150 );
lv_obj_set_y( ui_hour1, 0 );
lv_obj_set_align( ui_hour1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_hour1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_hour1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel2 = lv_obj_create(ui_digitalClock2);
lv_obj_set_width( ui_Panel2, 20);
lv_obj_set_height( ui_Panel2, 20);
lv_obj_set_x( ui_Panel2, 0 );
lv_obj_set_y( ui_Panel2, -20 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_digitalClock2);
lv_obj_set_width( ui_Panel3, 20);
lv_obj_set_height( ui_Panel3, 20);
lv_obj_set_x( ui_Panel3, 0 );
lv_obj_set_y( ui_Panel3, 20 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel3, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_minute1 = lv_img_create(ui_digitalClock2);
lv_img_set_src(ui_minute1, &ui_img_a_zero_png);
lv_obj_set_width( ui_minute1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_minute1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_minute1, 60 );
lv_obj_set_y( ui_minute1, 0 );
lv_obj_set_align( ui_minute1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_minute1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_minute1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_hour2 = lv_img_create(ui_digitalClock2);
lv_img_set_src(ui_hour2, &ui_img_a_zero_png);
lv_obj_set_width( ui_hour2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_hour2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_hour2, -60 );
lv_obj_set_y( ui_hour2, 0 );
lv_obj_set_align( ui_hour2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_hour2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_hour2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_digitalClock1 = lv_obj_create(ui_clockPanel);
lv_obj_set_width( ui_digitalClock1, 480);
lv_obj_set_height( ui_digitalClock1, 320);
lv_obj_set_align( ui_digitalClock1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_digitalClock1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_digitalClock1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_digitalClock1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_digitalClock1, lv_color_hex(0x121A37), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_digitalClock1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_digitalClock1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_analogClock = lv_obj_create(ui_clockPanel);
lv_obj_set_width( ui_analogClock, 480);
lv_obj_set_height( ui_analogClock, 320);
lv_obj_set_align( ui_analogClock, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_analogClock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_analogClock, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_analogClock, &ui_img_clock_large_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_width(ui_analogClock, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_hourHand1 = lv_img_create(ui_analogClock);
lv_img_set_src(ui_hourHand1, &ui_img_hour_h_png);
lv_obj_set_width( ui_hourHand1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_hourHand1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_hourHand1, 0 );
lv_obj_set_y( ui_hourHand1, -40 );
lv_obj_set_align( ui_hourHand1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_hourHand1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_hourHand1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_hourHand1,7,90);
lv_img_set_angle(ui_hourHand1,270);

ui_minuteHand1 = lv_img_create(ui_analogClock);
lv_img_set_src(ui_minuteHand1, &ui_img_minute_h_png);
lv_obj_set_width( ui_minuteHand1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_minuteHand1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_minuteHand1, 0 );
lv_obj_set_y( ui_minuteHand1, -40 );
lv_obj_set_align( ui_minuteHand1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_minuteHand1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_minuteHand1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_minuteHand1,7,90);
lv_img_set_angle(ui_minuteHand1,900);

ui_secondHand1 = lv_img_create(ui_analogClock);
lv_img_set_src(ui_secondHand1, &ui_img_second_h_png);
lv_obj_set_width( ui_secondHand1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_secondHand1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_secondHand1, 0 );
lv_obj_set_y( ui_secondHand1, -40 );
lv_obj_set_align( ui_secondHand1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_secondHand1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_secondHand1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_secondHand1,7,90);
lv_obj_set_style_img_recolor(ui_secondHand1, lv_color_hex(0xFF8300), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_secondHand1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_clockDot1 = lv_obj_create(ui_analogClock);
lv_obj_set_width( ui_clockDot1, 15);
lv_obj_set_height( ui_clockDot1, 15);
lv_obj_set_align( ui_clockDot1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_clockDot1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_clockDot1, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_clockDot1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_clockDot1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_clockDot1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_clockScreen, ui_event_clockScreen, LV_EVENT_ALL, NULL);

}

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_homeScreen_screen_init();
ui_clockScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_homeScreen);
}
