// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: Standby

#ifndef _STANDBY_UI_H
#define _STANDBY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_events.h"
void clockWise_Animation( lv_obj_t *TargetObject, int delay);
void pulseCall_Animation( lv_obj_t *TargetObject, int delay);
void textUpDown_Animation( lv_obj_t *TargetObject, int delay);
void textSide_Animation( lv_obj_t *TargetObject, int delay);
void ui_event_homeScreen( lv_event_t * e);
extern lv_obj_t *ui_homeScreen;
extern lv_obj_t *ui_clockSmallBackground;
extern lv_obj_t *ui_hourHand;
extern lv_obj_t *ui_minuteHand;
extern lv_obj_t *ui_secondHand;
extern lv_obj_t *ui_clockDot;
extern lv_obj_t *ui_infoPanel;
extern lv_obj_t *ui_weatherPanel;
extern lv_obj_t *ui_weatherCity;
extern lv_obj_t *ui_weatherTemperature;
extern lv_obj_t *ui_weatherIcon;
extern lv_obj_t *ui_weatherCondition;
extern lv_obj_t *ui_weatherRange;
extern lv_obj_t *ui_calendar;
extern lv_obj_t *ui_musicPanel;
void ui_event_previosButton( lv_event_t * e);
extern lv_obj_t *ui_previosButton;
void ui_event_playPause( lv_event_t * e);
extern lv_obj_t *ui_playPause;
void ui_event_nextButton( lv_event_t * e);
extern lv_obj_t *ui_nextButton;
void ui_event_volumeSlider( lv_event_t * e);
extern lv_obj_t *ui_volumeSlider;
extern lv_obj_t *ui_alertPanel;
extern lv_obj_t *ui_alertTitle;
extern lv_obj_t *ui_alertIcon;
extern lv_obj_t *ui_alertText;
extern lv_obj_t *ui_callPanel;
extern lv_obj_t *ui_callIcon;
extern lv_obj_t *ui_callText;
extern lv_obj_t *ui_callerName;
void ui_event_clockScreen( lv_event_t * e);
extern lv_obj_t *ui_clockScreen;
extern lv_obj_t *ui_clockPanel;
extern lv_obj_t *ui_digitalClock2;
extern lv_obj_t *ui_minute2;
extern lv_obj_t *ui_hour1;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_minute1;
extern lv_obj_t *ui_hour2;
extern lv_obj_t *ui_digitalClock1;
extern lv_obj_t *ui_analogClock;
extern lv_obj_t *ui_hourHand1;
extern lv_obj_t *ui_minuteHand1;
extern lv_obj_t *ui_secondHand1;
extern lv_obj_t *ui_clockDot1;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_clock_round_bg_png);   // assets\clock_round_bg.png
LV_IMG_DECLARE( ui_img_hour_h_png);   // assets\hour_h.png
LV_IMG_DECLARE( ui_img_minute_h_png);   // assets\minute_h.png
LV_IMG_DECLARE( ui_img_second_h_png);   // assets\second_h.png
LV_IMG_DECLARE( ui_img_602202963);   // assets\dy-7.png
LV_IMG_DECLARE( ui_img_back_png);   // assets\back.png
LV_IMG_DECLARE( ui_img_pause_png);   // assets\pause.png
LV_IMG_DECLARE( ui_img_next_png);   // assets\next.png
LV_IMG_DECLARE( ui_img_whatsapp_png);   // assets\whatsapp.png
LV_IMG_DECLARE( ui_img_answer_png);   // assets\answer.png
LV_IMG_DECLARE( ui_img_a_zero_png);   // assets\a_zero.png
LV_IMG_DECLARE( ui_img_clock_large_bg_png);   // assets\clock_large_bg.png
LV_IMG_DECLARE( ui_img_alipay_png);   // assets\alipay.png
LV_IMG_DECLARE( ui_img_brightness_png);   // assets\brightness.png
LV_IMG_DECLARE( ui_img_camera_png);   // assets\camera.png
LV_IMG_DECLARE( ui_img_cloudy_png);   // assets\cloudy.png
LV_IMG_DECLARE( ui_img_decline_png);   // assets\decline.png
LV_IMG_DECLARE( ui_img_602206286);   // assets\dy-0.png
LV_IMG_DECLARE( ui_img_602205261);   // assets\dy-1.png
LV_IMG_DECLARE( ui_img_602199888);   // assets\dy-2.png
LV_IMG_DECLARE( ui_img_602207311);   // assets\dy-3.png
LV_IMG_DECLARE( ui_img_602200913);   // assets\dy-5.png
LV_IMG_DECLARE( ui_img_602195540);   // assets\dy-6.png
LV_IMG_DECLARE( ui_img_dy4_png);   // assets\dy4.png
LV_IMG_DECLARE( ui_img_eight_png);   // assets\eight.png
LV_IMG_DECLARE( ui_img_facebook_png);   // assets\facebook.png
LV_IMG_DECLARE( ui_img_five_png);   // assets\five.png
LV_IMG_DECLARE( ui_img_four_png);   // assets\four.png
LV_IMG_DECLARE( ui_img_info_png);   // assets\info.png
LV_IMG_DECLARE( ui_img_instagram_png);   // assets\instagram.png
LV_IMG_DECLARE( ui_img_kakao_png);   // assets\kakao.png
LV_IMG_DECLARE( ui_img_1592976543);   // assets\left-arrow.png
LV_IMG_DECLARE( ui_img_line_png);   // assets\line.png
LV_IMG_DECLARE( ui_img_mail_png);   // assets\mail.png
LV_IMG_DECLARE( ui_img_messenger_png);   // assets\messenger.png
LV_IMG_DECLARE( ui_img_nine_png);   // assets\nine.png
LV_IMG_DECLARE( ui_img_notify_png);   // assets\notify.png
LV_IMG_DECLARE( ui_img_229834011);   // assets\nt-0.png
LV_IMG_DECLARE( ui_img_229835036);   // assets\nt-1.png
LV_IMG_DECLARE( ui_img_229827613);   // assets\nt-2.png
LV_IMG_DECLARE( ui_img_229828638);   // assets\nt-3.png
LV_IMG_DECLARE( ui_img_229838359);   // assets\nt-4.png
LV_IMG_DECLARE( ui_img_229839384);   // assets\nt-5.png
LV_IMG_DECLARE( ui_img_229831961);   // assets\nt-6.png
LV_IMG_DECLARE( ui_img_229832986);   // assets\nt-7.png
LV_IMG_DECLARE( ui_img_one_png);   // assets\one.png
LV_IMG_DECLARE( ui_img_paypal_png);   // assets\paypal.png
LV_IMG_DECLARE( ui_img_penguin_png);   // assets\penguin.png
LV_IMG_DECLARE( ui_img_play_png);   // assets\play.png
LV_IMG_DECLARE( ui_img_qr_png);   // assets\qr.png
LV_IMG_DECLARE( ui_img_2138854088);   // assets\right-arrow.png
LV_IMG_DECLARE( ui_img_search_png);   // assets\search.png
LV_IMG_DECLARE( ui_img_setting_png);   // assets\setting.png
LV_IMG_DECLARE( ui_img_seven_png);   // assets\seven.png
LV_IMG_DECLARE( ui_img_six_png);   // assets\six.png
LV_IMG_DECLARE( ui_img_skype_png);   // assets\skype.png
LV_IMG_DECLARE( ui_img_sms_png);   // assets\sms.png
LV_IMG_DECLARE( ui_img_telegram_png);   // assets\telegram.png
LV_IMG_DECLARE( ui_img_three_png);   // assets\three.png
LV_IMG_DECLARE( ui_img_timeout_png);   // assets\timeout.png
LV_IMG_DECLARE( ui_img_twitter_png);   // assets\twitter.png
LV_IMG_DECLARE( ui_img_two_png);   // assets\two.png
LV_IMG_DECLARE( ui_img_viber_png);   // assets\viber.png
LV_IMG_DECLARE( ui_img_vkontakte_png);   // assets\vkontakte.png
LV_IMG_DECLARE( ui_img_wechat_png);   // assets\wechat.png
LV_IMG_DECLARE( ui_img_wechat_pay_png);   // assets\wechat_pay.png
LV_IMG_DECLARE( ui_img_weibo_png);   // assets\weibo.png
LV_IMG_DECLARE( ui_img_zero_png);   // assets\zero.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
