// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: Standby

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void homeScreenLoaded(lv_event_t * e);
void musicPrevious(lv_event_t * e);
void musicToggle(lv_event_t * e);
void musicNext(lv_event_t * e);
void volumeChanged(lv_event_t * e);
void clockScreenLoaded(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
